# Site settings
title: GisBusters-awesome Maps
email: gisbusters@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are GisBusters. We make maps!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://gisbusters.com" # the base hostname & protocol for your site
twitter_username: gisbusters
github_username:  gisbusters

# Build settings
markdown: redcarpet
